import test from 'node:test';
import assert from 'node:assert/strict';
import {canonicalStatus} from '../supabase/functions/billsavings-checkout/checkout-state.mjs';
const offers={premium:{amount:199,product:'prod_VG0psHDVZ0MSLl'},family:{amount:499,product:'prod_VG0q8LK19CVtkB'}};
function checkout(plan='premium') {const o=offers[plan];return {id:'cs_live_syntheticSubscriptionSession123456789',livemode:true,mode:'subscription',currency:'usd',amount_total:null,status:'open',payment_status:'unpaid',metadata:{app:'billsavings_ai',offer:plan,price_version:'us-low-20261003',checkout_channel:'qr',owner_hash:'a'.repeat(64)},line_items:{has_more:false,data:[{quantity:1,price:{livemode:true,currency:'usd',unit_amount:o.amount,product:o.product,recurring:{interval:'month',interval_count:1}}}]}};}
const options={app:'billsavings_ai',mode:'subscription',offers,ownerHash:'a'.repeat(64),qrOnly:true};
test('unpaid subscription with null totals remains open after its exact monthly product price is verified',()=>{for(const plan of ['premium','family']){const s=checkout(plan);assert.equal(canonicalStatus(s,options).status,'open');s.currency=null;assert.equal(canonicalStatus(s,options).status,'open');}});
test('no access is granted when a completed subscription is unpaid or has null or incorrect totals',()=>{const s=checkout();for(const amount of [null,0,198,499])assert.throws(()=>canonicalStatus({...s,status:'complete',payment_status:'paid',amount_total:amount},options));assert.equal(canonicalStatus({...s,status:'complete',amount_total:199},options).status,'processing');assert.equal(canonicalStatus({...s,status:'complete',payment_status:'paid',amount_total:199},options).status,'paid');});
test('a null total never permits a different price, product, currency, quantity or recurrence',()=>{for(const field of ['amount','product','currency','quantity','interval','missing_items']){const s=checkout();const item=s.line_items.data[0];if(field==='amount')item.price.unit_amount=1;if(field==='product')item.price.product='prod_other';if(field==='currency')item.price.currency='eur';if(field==='quantity')item.quantity=2;if(field==='interval')item.price.recurring.interval='week';if(field==='missing_items')delete s.line_items;assert.throws(()=>canonicalStatus(s,options),field);}});
