'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const crypto=require('node:crypto');
const html=fs.readFileSync('bill-compare.html','utf8');
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS '+name);}
const scripts=[...html.matchAll(/<script id="[^"]+">([\s\S]*?)<\/script>/g)].map(x=>x[1]);
const context=vm.createContext({Intl});
vm.runInContext(scripts[0],context);
const B=context.BillDiff;
test('script syntax',()=>scripts.forEach(code=>new vm.Script(code)));
test('integer cents',()=>assert.equal(B.cents('0.10')+B.cents('0.20'),30));
test('thousands and cents',()=>assert.equal(B.cents('$1,234.50'),123450));
test('credits and zero',()=>{assert.equal(B.cents('-$20.00'),-2000);assert.equal(B.cents('(20.00)'),-2000);assert.equal(B.cents('0'),0);});
test('invalid and ambiguous amounts rejected',()=>{for(const s of ['','abc','12,50','1,00.00','1.123','NaN','Infinity','--2','(-2)','1e3','1000001'])assert.throws(()=>B.cents(s));});
test('duplicate labels blocked',()=>assert.throws(()=>B.parse('Service fee | 10\n SERVICE   FEE | 20','Older')));
test('totals are not counted as items',()=>assert.throws(()=>B.parse('Total | 50','Older')));
test('missing inputs blocked',()=>{assert.throws(()=>B.parse('Service |','Older'));assert.throws(()=>B.parse(' ','Older'));});
test('BOM and CRLF',()=>assert.equal(B.parse('\uFEFFPlan | 2.00\r\nCredit | -1.00','Old').length,2));
test('item count bound',()=>assert.throws(()=>B.parse(Array.from({length:151},(_,i)=>'Item '+i+' | 1').join('\n'),'Old')));
test('missing credit increases selected costs',()=>{const d=B.compare(B.parse('Plan | 70\nPromo | -20\nEquipment | 10','Old'),B.parse('PLAN | 82\nEquipment | 15','New'));assert.equal(d.before,6000);assert.equal(d.after,9700);assert.equal(d.difference,3700);assert.equal(d.rows.find(x=>x.label==='Promo').status,'Credit no longer listed');assert.equal(d.rows.reduce((s,x)=>s+x.difference,0),d.difference);});
test('zero is not missing',()=>{const d=B.compare(B.parse('Credit | -5','Old'),B.parse('Credit | 0','New'));assert.equal(d.rows[0].status,'Cost increased');assert.notEqual(d.rows[0].new,null);});
test('no silent fuzzy matching',()=>{const d=B.compare(B.parse('Old label | 10','Old'),B.parse('New label | 10','New'));assert.equal(d.rows.length,2);assert.equal(d.difference,0);});
test('new credit',()=>{const d=B.compare(B.parse('Plan | 10','Old'),B.parse('Plan | 10\nDiscount | -2','New'));assert.equal(d.rows.find(x=>x.label==='Discount').status,'New credit');});
test('CSP hashes match executable code and styles',()=>{for(const match of html.matchAll(/<(?:script id="[^"]+"|style)>([\s\S]*?)<\/(?:script|style)>/g)){const hash=crypto.createHash('sha256').update(match[1]).digest('base64');assert.ok(html.includes("'sha256-"+hash+"'"));}});
test('no dynamic HTML sinks',()=>assert.ok(!/\.innerHTML\s*=|insertAdjacentHTML/.test(html)));
test('no document persistence APIs',()=>assert.ok(!/localStorage|sessionStorage|indexedDB|setItem\(/.test(html)));
test('no document network API calls',()=>assert.ok(!/\bfetch\(|XMLHttpRequest|sendBeacon\(/.test(html)));
test('sitemap discovery',()=>assert.ok(fs.readFileSync('sitemap-growth.xml','utf8').includes('https://billsavingsai.com/bill-compare.html')));
console.log(passed+' isolated comparison tests passed.');
