const input=document.getElementById('csvFile');const run=document.getElementById('runAudit');const status=document.getElementById('status');const results=document.getElementById('results');let text='';
input.addEventListener('change',async()=>{const f=input.files?.[0];results.hidden=true;if(!f){text='';run.disabled=true;status.textContent='Choose a CSV to begin.';return}if(f.size>8*1024*1024){text='';run.disabled=true;status.textContent='Use a CSV smaller than 8 MB.';return}text=await f.text();run.disabled=!text.trim();status.textContent=`${f.name} selected. This preview runs locally in your browser.`});
run.addEventListener('click',()=>{try{const rows=parseCSV(text);const a=analyze(rows);render(a);status.textContent=`Audit complete. Reviewed ${a.txCount} parsed transaction rows locally.`}catch(e){results.hidden=true;status.textContent=e.message||'Could not analyze this CSV.'}});
function parseCSV(t){const lines=t.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error('CSV needs a header and at least one transaction.');const d=detectDelimiter(lines[0]);const h=split(lines[0],d).map(x=>x.trim().toLowerCase());const vi=find(h,['description','vendor','merchant','name','payee','memo']);const ai=find(h,['amount','transaction amount','debit','charge','value']);const di=find(h,['date','transaction date','posted date','posting date']);if(vi<0||ai<0)throw new Error('Could not detect Description/Vendor and Amount columns.');return lines.slice(1).map(line=>{const c=split(line,d);const raw=(c[ai]||'').replace(/[$,\s]/g,'').replace(/[()]/g,m=>m==='('?'-':'');const amount=Math.abs(Number(raw.replace(')','')));const vendor=(c[vi]||'').trim();const date=di>=0?new Date((c[di]||'').trim()):null;return{vendor,amount,date:date&&!isNaN(date)?date:null}}).filter(r=>r.vendor&&Number.isFinite(r.amount)&&r.amount>0)}
function detectDelimiter(line){return [',',';','\t'].sort((a,b)=>line.split(b).length-line.split(a).length)[0]}function split(line,d){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(ch===d&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out}function find(h,names){for(const n of names){const x=h.indexOf(n);if(x>=0)return x}return h.findIndex(x=>names.some(n=>x.includes(n)))}
function norm(v){return v.toLowerCase().replace(/\b(inc|llc|ltd|corp|corporation|payment|purchase|pos|online)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim()}
function analyze(rows){if(!rows.length)throw new Error('No usable rows found.');const by=new Map(),seen=new Map(),duplicates=[],recurring=[],increases=[];let monthly=0;rows.forEach(r=>{const k=norm(r.vendor);if(!by.has(k))by.set(k,[]);by.get(k).push(r);const d=r.date?r.date.toISOString().slice(0,10):'no-date';const ek=`${k}|${r.amount.toFixed(2)}|${d}`;if(seen.has(ek))duplicates.push({vendor:r.vendor,detail:`Possible duplicate ${money(r.amount)}. Verify the original statement.`});else seen.set(ek,r)});for(const txs of by.values()){txs.sort((a,b)=>(a.date?.getTime()||0)-(b.date?.getTime()||0));if(txs.length<2)continue;const amounts=txs.map(x=>x.amount);const avg=amounts.reduce((a,b)=>a+b,0)/amounts.length;const dated=txs.filter(x=>x.date);let monthlyLike=false;if(dated.length>=2){for(let i=1;i<dated.length;i++){const days=Math.abs((dated[i].date-dated[i-1].date)/86400000);if(days>=20&&days<=40)monthlyLike=true}}else if(txs.length>=3)monthlyLike=true;if(monthlyLike){recurring.push({vendor:txs[0].vendor,detail:`${txs.length} similar charges found · est. ${money(avg)}/month`});monthly+=avg}const first=amounts[0],last=amounts[amounts.length-1];if(first>0&&last>first*1.05){increases.push({vendor:txs.at(-1).vendor,detail:`Recent charge is about ${(((last-first)/first)*100).toFixed(0)}% higher than the earliest charge in this file.`})}}return{txCount:rows.length,duplicates:uniq(duplicates),recurring:uniq(recurring),increases:uniq(increases),monthly}}
function uniq(arr){const m=new Map();arr.forEach(x=>{const k=norm(x.vendor)+x.detail;if(!m.has(k))m.set(k,x)});return[...m.values()]}
function money(n){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n||0)}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(a){const flags=[...a.duplicates.map(x=>['Possible duplicate',x]),...a.increases.map(x=>['Price increase',x]),...a.recurring.map(x=>['Recurring vendor',x])].slice(0,12);results.innerHTML=`<div class="result"><b>${a.duplicates.length+a.increases.length+a.recurring.length} flags · ${a.recurring.length} recurring vendors</b><span>Estimated recurring spend detected: ${money(a.monthly)}</span></div>${flags.map(([t,x])=>`<div class="result"><b>${esc(t)} · ${esc(x.vendor)}</b><span>${esc(x.detail)}</span></div>`).join('')||'<div class="result"><b>No obvious flags in this preview.</b><span>That does not prove there are no savings opportunities.</span></div>'}<div class="result"><b>Important</b><span>Informational screening only. Verify every finding against original records before taking action.</span></div>`;results.hidden=false}
